version: "3.9"

name:
  blossom-single

services:
  blossom-backend:
    image: jasminexzzz/blossom:latest
    container_name: blossom-backend
    volumes:
      # 挂载图片保存路径，如果是windows环境，可以使用/c/home/bl/img/来指定磁盘
      - ${BLOSSOM_MOUNT}:/data
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # 配置数据库访问地址
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
      # 配置数据库用户名
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      # 配置数据库密码
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      # 配置图片保存的磁盘路径，并在 volumes 中将该路径挂载为本地路径，如上方 volumes 中的示例
      PROJECT_IAAS_BLOS_DEFAULT-PATH: /data/img/
    ports:
      - "9999:9999"
    restart: always
