version: '3.8'

services:
  nexus:
    image: klo2k/nexus3:latest
    container_name: nexus
    ports:
      # 8081是服务常用端口, 避免占用
      - '28081:8081'
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      # 8080 是SpringWeb默认端口, 使用28080避免占用
      - "28080:8080"
      - "50000:50000"
    volumes:
      # 允许Jenkins访问Docker服务
      - "/var/run/docker.sock:/var/run/docker.sock"